steps:
-  name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/service-exploration-lab-345921/afaras-awesome-project:$SHORT_SHA', '.']
-  name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/service-exploration-lab-345921/afaras-awesome-project:$SHORT_SHA']
-  name: 'gcr.io/cloud-builders/gcloud'
   args: ['beta', 'run', 'deploy', 'afaras-awesome-project', '--region=us-central1', '--platform=managed', '--image=gcr.io/service-exploration-lab-345921/afaras-awesome-project:$SHORT_SHA']
